Bug fix: Prevent OrderBook on change event
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/GDAX-Python/gdax/websocket_client.py", line 41, in _go
    self._listen()
  File "/GDAX-Python/gdax/websocket_client.py", line 72, in _listen
    self.on_message(msg)
  File "/py3playground/cryptocurrencies/gdax_order_book.py", line 30, in on_message
    super(OrderBookConsole, self).on_message(message)
  File "/GDAX-Python/gdax/order_book.py", line 78, in on_message
    self.change(message)
  File "/GDAX-Python/gdax/order_book.py", line 172, in change
    index = map(itemgetter('id'), bids).index(order['order_id'])
AttributeError: 'map' object has no attribute 'index'

Solution:
This map needed to be converted into a list(). Here is a simple repro:

In [1]: from operator import itemgetter

In [2]: a = [{'id': 0, 'value': 'zero'}, {'id': 1, 'value': 'one'}]

In [3]: map(itemgetter('id'), a)
Out[3]: <map at 0x10f5f91d0>

In [4]: list(map(itemgetter('id'), a))
Out[4]: [0, 1]

Also, DRYed up code and removed dead code.